pub mod canonical;
mod closeout;
pub mod engine;
pub mod error;
mod history;
pub mod identity;
mod runtime;
pub mod store;

pub use canonical::{
    CanonicalValue, WorkState, canonical_bytes, content_object_digest, entity_version_digest,
    parse_canonical_json, relation_version_digest, validate_import_fixed_point,
    work_state_mapping_digest,
};
pub use closeout::{
    CLOSEOUT_INSPECT_DEFAULT_BUDGET, CLOSEOUT_INSPECT_MAX_BUDGET,
    CloseoutInspectAcceptanceCriterionItem, CloseoutInspectAuthorizationReceiptItem,
    CloseoutInspectBranchHeadProof, CloseoutInspectBudgetReport, CloseoutInspectCategory,
    CloseoutInspectClaimItem, CloseoutInspectContainmentItem, CloseoutInspectCounts,
    CloseoutInspectDirectPlanItem, CloseoutInspectDirectTaskItem,
    CloseoutInspectEvidenceContentItem, CloseoutInspectEvidenceItem, CloseoutInspectGap,
    CloseoutInspectGapCategory, CloseoutInspectGoalCounts, CloseoutInspectGoalItem,
    CloseoutInspectGoalProjection, CloseoutInspectHandoffItem, CloseoutInspectNonExpanded,
    CloseoutInspectNonExpandedCategory, CloseoutInspectOmitted, CloseoutInspectOptions,
    CloseoutInspectPlanCounts, CloseoutInspectPlanItem, CloseoutInspectPlanProjection,
    CloseoutInspectReadDrift, CloseoutInspectReadObservation, CloseoutInspectReadProof,
    CloseoutInspectResolvedSource, CloseoutInspectRuntimeCounts, CloseoutInspectRuntimeGap,
    CloseoutInspectRuntimeGapCategory, CloseoutInspectRuntimeSummary, CloseoutInspectSessionItem,
    CloseoutInspectSource, CloseoutInspectSourceKind, CloseoutInspectStoreFileKind,
    CloseoutInspectStoreFileMetadata, CloseoutInspectTarget, CloseoutInspectTargetDigestStatus,
    CloseoutInspectTargetKind, CloseoutInspectTargetResolution, CloseoutInspectTaskItem,
    CloseoutInspectTaskProjection, CloseoutInspectVerificationItem,
    CloseoutInspectVerificationRequirementItem, CloseoutInspectVerificationTargetKind,
};
pub use engine::Engine;
pub use error::{ErrorCategory, ErrorCode, Result, WorkVcsError};
pub use history::{
    AcceptanceCriterionClassification, AcceptanceCriterionCreateCommit,
    AcceptanceCriterionCreateOptions, AcceptanceCriterionEffectiveStatus,
    AcceptanceCriterionRevisionCommit, AcceptanceCriterionRevisionOptions,
    AcceptanceCriterionSnapshot, AcceptanceCriterionState,
    AcceptanceCriterionVerificationRequirementRef, ApplicabilityResourceObservationStatus,
    ApplicabilityResourceStampInput, ApplicabilityResourceStampSnapshot,
    AuthorizationReceiptAuthorityRefManifest, AuthorizationReceiptBinding,
    AuthorizationReceiptConsumeManifest, AuthorizationReceiptConsumeOptions,
    AuthorizationReceiptConsumeOutcome, AuthorizationReceiptConsumeResult,
    AuthorizationReceiptIssueManifest, AuthorizationReceiptIssueOptions,
    AuthorizationReceiptIssueResult, AuthorizationReceiptListOptions,
    AuthorizationReceiptListResult, AuthorizationReceiptOutcome,
    AuthorizationReceiptRelationResult, AuthorizationReceiptRelationSnapshot,
    AuthorizationReceiptResult, AuthorizationReceiptSnapshot, AuthorizationReceiptTargetManifest,
    BranchForkOptions, BranchForkResult, BranchForkSource, BranchHead,
    BranchProjectionRefreshOptions, BranchProjectionRefreshResult, BranchProjectionSnapshot,
    BranchProjectionStatus, BundleAcceptanceCriterionIdentityRef, BundleBranchHeadPreflightDetail,
    BundleBranchHeadRef, BundleChangeSetCausalAnchorRef, BundleCheckpointCandidate,
    BundleEntityMembershipChangeRef, BundleEntityVersionRef, BundleExportManifest,
    BundleExportOptions, BundleImportApplyOptions, BundleImportApplyResult,
    BundleImportAttemptListOptions, BundleImportAttemptListResult, BundleImportAttemptOptions,
    BundleImportAttemptOutcomeSnapshot, BundleImportAttemptResult, BundleImportAttemptSnapshot,
    BundleImportPreflightOptions, BundleImportPreflightResult,
    BundleKnowledgeExposureLocalSourceRef, BundleKnowledgeExposureRef,
    BundleKnowledgeExposureSourceStatusRef, BundleKnowledgeExposureTransitionRef,
    BundleKnowledgeSpaceRef, BundleManifestValidationOptions, BundleManifestValidationResult,
    BundlePayloadExport, BundlePayloadExportOptions, BundlePayloadFile, BundlePayloadInput,
    BundlePayloadReference, BundlePayloadValidationOptions, BundlePayloadValidationResult,
    BundlePortableEvidenceContentRef, BundleRelationMembershipChangeRef, BundleRelationVersionRef,
    BundleVerificationRequirementIdentityRef, ChangeOperationListResult, ChangeOperationSnapshot,
    ChangeOperationSubject, ChangeSetCausalAnchorListResult, ChangeSetCausalAnchorSnapshot,
    ChangeSetCommitSnapshot, ChangeSetSnapshot, CheckpointCreateOptions, CheckpointCreateResult,
    CheckpointLatestOptions, CheckpointLatestResult, CheckpointListOptions, CheckpointListResult,
    CheckpointSnapshot, CheckpointValidationResult, CognitionCaptureEntityResult,
    CognitionCaptureEvidenceResult, CognitionCaptureKnowledgeManifest, CognitionCaptureManifest,
    CognitionCaptureOptions, CognitionCaptureOutcome, CognitionCaptureRelationManifest,
    CognitionCaptureRelationResult, CognitionCaptureResult, CommitParentSnapshot, CommitSnapshot,
    ContentStorageLocationSnapshot, DEFAULT_RECORD_CURRENTNESS_AUDIT_BUDGET,
    DecisionRecordSupersedeCommit, DecisionRecordSupersedeOptions, EntityTransitionCommit,
    EntityTransitionOptions, EntityVersionDiff, EventListOptions, EventListResult, EventListTarget,
    EventSnapshot, EvidenceContentInput, EvidenceContentReadResult, EvidenceContentSnapshot,
    EvidenceCreateOptions, EvidenceCreateResult, EvidenceListOptions, EvidenceListResult,
    EvidenceSnapshot, ExternalObjectRefListOptions, ExternalObjectRefListResult,
    ExternalObjectRefRecordOptions, ExternalObjectRefRecordResult, ExternalObjectRefSnapshot,
    ExternalObjectReferenceScope, FindingRecordCorrectionCommit, FindingRecordCorrectionOptions,
    GoalCreateCommit, GoalCreateOptions, GoalSnapshot, GoalState, GoalStatus, GoalTransitionCommit,
    GoalTransitionOptions, HistoryEntry, HistoryQueryOptions, HistoryQueryResult, HistoryStart,
    IntegrityReport, KnowledgeCreateCommit, KnowledgeCreateOptions, KnowledgeExposureAdoptOptions,
    KnowledgeExposureAdoptResult, KnowledgeExposureAdoptionCandidate,
    KnowledgeExposureAdoptionCandidateOptions, KnowledgeExposureAdoptionCandidateResult,
    KnowledgeExposureCreateLocalOptions, KnowledgeExposureCreateResult,
    KnowledgeExposureDerivedFromRelationCreateCommit,
    KnowledgeExposureDerivedFromRelationCreateOptions, KnowledgeExposureLifecycleStatus,
    KnowledgeExposureListOptions, KnowledgeExposureListResult,
    KnowledgeExposureLocalSourceSnapshot, KnowledgeExposureRefreshSourceStatusOptions,
    KnowledgeExposureRefreshSourceStatusResult, KnowledgeExposureSnapshot,
    KnowledgeExposureSourceStatus, KnowledgeExposureSourceStatusSnapshot,
    KnowledgeExposureWithdrawOptions, KnowledgeExposureWithdrawResult, KnowledgeListOptions,
    KnowledgeListResult, KnowledgeRelationCreateCommit, KnowledgeRelationCreateOptions,
    KnowledgeRelationListOptions, KnowledgeRelationListResult, KnowledgeRelationRemoveCommit,
    KnowledgeRelationRemoveOptions, KnowledgeRelationRestoreCommit,
    KnowledgeRelationRestoreOptions, KnowledgeRelationSnapshot, KnowledgeSnapshot,
    KnowledgeSpaceAvailableExposuresOptions, KnowledgeSpaceAvailableExposuresResult,
    KnowledgeSpaceCreateOptions, KnowledgeSpaceCreateResult,
    KnowledgeSpaceHistoricalExposuresOptions, KnowledgeSpaceHistoricalExposuresResult,
    KnowledgeSpaceListOptions, KnowledgeSpaceListResult,
    KnowledgeSpaceRefreshSourceStatusesOptions, KnowledgeSpaceRefreshSourceStatusesResult,
    KnowledgeSpaceSnapshot, KnowledgeSpaceSourceStaleExposuresOptions,
    KnowledgeSpaceSourceStaleExposuresResult, KnowledgeState, KnowledgeStatus,
    KnowledgeTransitionCommit, KnowledgeTransitionOptions, MAX_RECORD_CURRENTNESS_AUDIT_BUDGET,
    PlanAdmissionAcceptanceCriterionManifest, PlanAdmissionAcceptanceCriterionResult,
    PlanAdmissionEntityResult, PlanAdmissionEvidenceManifest, PlanAdmissionEvidenceResult,
    PlanAdmissionGoalManifest, PlanAdmissionGoalResult, PlanAdmissionManifest,
    PlanAdmissionOptions, PlanAdmissionOutcome, PlanAdmissionPlanManifest,
    PlanAdmissionRecordManifest, PlanAdmissionRecordResult, PlanAdmissionResult,
    PlanAdmissionTaskManifest, PlanAdmissionTaskResult,
    PlanAdmissionVerificationRequirementManifest, PlanAdmissionVerificationRequirementResult,
    PlanCreateCommit, PlanCreateOptions, PlanEvolutionInPlaceManifest, PlanEvolutionManifest,
    PlanEvolutionOptions, PlanEvolutionOutcome, PlanEvolutionPlanResult,
    PlanEvolutionPlanUpdateManifest, PlanEvolutionRelationResult, PlanEvolutionResult,
    PlanEvolutionSupersedeConstraintsManifest, PlanEvolutionSupersedeManifest,
    PlanEvolutionSupersedePlanManifest, PlanSnapshot, PlanState, PlanStatus,
    PlanSupersedesRelationSnapshot, PlanTransitionCommit, PlanTransitionOptions,
    PrimaryContainmentCreateCommit, PrimaryContainmentCreateOptions,
    PrimaryContainmentEndpointKind, PrimaryContainmentSnapshot, RecordCreateCommit,
    RecordCreateOptions, RecordCurrentnessAuditCounts, RecordCurrentnessAuditItem,
    RecordCurrentnessAuditOptions, RecordCurrentnessAuditResult, RecordCurrentnessClass,
    RecordKind, RecordKnowledgeRelationCreateCommit, RecordKnowledgeRelationCreateOptions,
    RecordKnowledgeRelationListOptions, RecordKnowledgeRelationListResult,
    RecordKnowledgeRelationRemoveCommit, RecordKnowledgeRelationRemoveOptions,
    RecordKnowledgeRelationRestoreCommit, RecordKnowledgeRelationRestoreOptions,
    RecordKnowledgeRelationSnapshot, RecordListOptions, RecordListResult,
    RecordRelationCreateCommit, RecordRelationCreateOptions, RecordRelationListOptions,
    RecordRelationListResult, RecordRelationRemoveCommit, RecordRelationRemoveOptions,
    RecordRelationRestoreCommit, RecordRelationRestoreOptions, RecordRelationSnapshot,
    RecordRelationType, RecordSnapshot, RecordState, RecordStatus, RecordTransitionCommit,
    RecordTransitionOptions, RelationVersionDiff, ReplayedState, ResolvedWhyQuerySubject,
    ResolvedWhyQueryTarget, ResolvedWorkStateDiffTarget, ResourceBindOptions, ResourceBindResult,
    ResourceBindingSnapshot, ResourceCreateOptions, ResourceCreateResult, ResourceListOptions,
    ResourceListResult, ResourceObservationCreateOptions, ResourceObservationCreateResult,
    ResourceObservationDetailInput, ResourceObservationDetailSnapshot,
    ResourceObservationListOptions, ResourceObservationListResult, ResourceObservationSnapshot,
    ResourceSnapshot, StoreLineageListOptions, StoreLineageListResult, StoreLineageRecordOptions,
    StoreLineageRecordResult, StoreLineageSnapshot, StoreMigrationAttemptSnapshot,
    StoreMigrationListOptions, StoreMigrationListResult, StoreMigrationOutcomeSnapshot,
    StoreMigrationRecordOptions, StoreMigrationRecordResult, StructuralReferenceCreateCommit,
    StructuralReferenceCreateOptions, StructuralReferenceEndpointKind, StructuralReferenceSnapshot,
    TaskAcceptanceCriterionRef, TaskCreateCommit, TaskCreateOptions,
    TaskSchedulingRelationCreateCommit, TaskSchedulingRelationCreateOptions,
    TaskSchedulingRelationSnapshot, TaskSchedulingRelationType, TaskSnapshot, TaskState,
    TaskStatus, TaskTransitionCommit, TaskTransitionOptions, VerificationApplicability,
    VerificationApplicabilityCacheListOptions, VerificationApplicabilityCacheListResult,
    VerificationApplicabilityCacheSnapshot, VerificationApplicabilityRecordOptions,
    VerificationApplicabilityRefreshOptions, VerificationCreateCommit, VerificationCreateOptions,
    VerificationEvidenceRef, VerificationEvidenceRelationCreate,
    VerificationEvidenceRelationSnapshot, VerificationRequirementCreateCommit,
    VerificationRequirementCreateOptions, VerificationRequirementRevisionCommit,
    VerificationRequirementRevisionOptions, VerificationRequirementSnapshot,
    VerificationRequirementState, VerificationResourceBasis, VerificationResult,
    VerificationSemanticDependency, VerificationSnapshot, VerificationState, VerificationTarget,
    WhyCausalAnchorChangeSet, WhyDeferredRelationFamily, WhyEntityKind, WhyEpistemicExplanation,
    WhyEvolutionChangeOperation, WhyEvolutionSubjectDetail, WhyEvolutionSubjectEntityDetail,
    WhyEvolutionSubjectRelationDetail, WhyQueryOptions, WhyQueryResult, WhyQuerySubject,
    WhyQueryTarget, WhyRelationDirection, WhyRelationEdge, WhyRelationEndpoint, WhyRelationKind,
    WhyScopeLink, WhyScopeLinkKind, WhyVerificationClosureChain, WorkStateDiff,
    WorkStateDiffChangeKind, WorkStateDiffOptions, WorkStateDiffTarget, WorkStateRestoreCommit,
    WorkStateRestoreOptions, WorkspaceInfo, WorkspaceInitOptions, WorkspaceListOptions,
    WorkspaceListResult, WorkspaceResourceAssociationListOptions,
    WorkspaceResourceAssociationListResult, WorkspaceResourceAssociationOptions,
    WorkspaceResourceAssociationResult, WorkspaceResourceAssociationSnapshot,
};
pub use identity::{
    BranchId, ChangeSetId, CheckpointId, ClaimId, CommitId, ContextPacketId, Digest, EntityId,
    EntityVersionId, EventId, EvidenceId, ExposureId, ExposureTransitionId, ExternalObjectId,
    ExternalRefId, ExternalVersionId, ImportId, KnowledgeSpaceId, LineageId, MergeId, MergeItemId,
    MigrationId, OperationId, RelationId, RelationVersionId, ResourceId, ResourceObservationId,
    SessionDiffId, SessionId, StoreId, WorkspaceId,
};
pub use runtime::{
    ClaimForceTakeoverOptions, ClaimForceTakeoverResult, ClaimGuardAction, ClaimGuardOptions,
    ClaimGuardReason, ClaimGuardResult, ClaimLifecycleState, ClaimListOptions, ClaimListResult,
    ClaimMode, ClaimNextOptions, ClaimNextResult, ClaimReleaseOptions, ClaimReleaseResult,
    ClaimSnapshot, ClaimTaskOptions, ClaimTaskResult, ClaimTransferOptions, ClaimTransferResult,
};
pub use runtime::{
    ContextItem, ContextItemCategory, ContextItemSubject, ContextOmissionBucket,
    ContextOmissionCategory, ContextOmissionSummary, ContextOverview, ContextOverviewOptions,
    ContextPacket, ContextPacketEnvelope, ContextPacketListOptions, ContextPacketListResult,
    ContextPacketOptions, ContextPacketSaveResult, ContextPacketSnapshot, ContextPriority,
    ContextProfile,
};
pub use runtime::{
    MergeAbortOptions, MergeAbortResult, MergeAttemptSnapshot, MergeContinueOptions,
    MergeContinueResult, MergeFreezeResolutionsOptions, MergeFreezeResolutionsResult,
    MergeItemClassification, MergeItemResolutionSnapshot, MergeItemSnapshot, MergeItemSubject,
    MergeListOptions, MergeListResult, MergeOutcome, MergeOutcomeSnapshot, MergeResolutionKind,
    MergeResolveOptions, MergeResolveResult, MergeRuntimeState, MergeStartOptions,
    MergeStartResult,
};
pub use runtime::{NextWorkOptions, NextWorkResult};
pub use runtime::{
    RunnableTaskBlockedReason, RunnableTaskCandidate, RunnableTaskClaimCoordination,
    RunnableTaskProjectionDimension, RunnableTasksOptions, RunnableTasksProjection,
};
pub use runtime::{
    SessionDiffSnapshot, SessionEndOptions, SessionEndResult, SessionFocus, SessionFocusOptions,
    SessionFocusPathEntry, SessionFocusUpdateResult, SessionLifecycleState, SessionListOptions,
    SessionListResult, SessionMarkStaleOptions, SessionMarkStaleResult, SessionSnapshot,
    SessionStartOptions, SessionStartResult, SessionSwitchOptions, SessionSwitchResult,
};
pub use runtime::{VerifyOptions, VerifyResourceObservationInput, VerifyResult};
pub use store::{
    ContextPacketSnapshotSchemaMigrationResult, StoreInfo, StoreInitOptions, StoreManifest,
};
