pub mod canonical;
pub mod engine;
pub mod error;
mod history;
pub mod identity;
mod runtime;
pub mod store;

pub use canonical::{
    CanonicalValue, WorkState, canonical_bytes, content_object_digest, entity_version_digest,
    parse_canonical_json, relation_version_digest, validate_import_fixed_point,
    work_state_mapping_digest,
};
pub use engine::Engine;
pub use error::{ErrorCategory, ErrorCode, Result, WorkVcsError};
pub use history::{
    AcceptanceCriterionClassification, AcceptanceCriterionCreateCommit,
    AcceptanceCriterionCreateOptions, AcceptanceCriterionEffectiveStatus,
    AcceptanceCriterionRevisionCommit, AcceptanceCriterionRevisionOptions,
    AcceptanceCriterionSnapshot, AcceptanceCriterionState,
    AcceptanceCriterionVerificationRequirementRef, ApplicabilityResourceObservationStatus,
    ApplicabilityResourceStampInput, ApplicabilityResourceStampSnapshot, BranchForkOptions,
    BranchForkResult, BranchForkSource, BranchHead, BranchProjectionRefreshOptions,
    BranchProjectionRefreshResult, BranchProjectionSnapshot, BranchProjectionStatus,
    BundleAcceptanceCriterionIdentityRef, BundleBranchHeadRef, BundleCheckpointCandidate,
    BundleEntityMembershipChangeRef, BundleEntityVersionRef, BundleExportManifest,
    BundleExportOptions, BundleImportApplyOptions, BundleImportApplyResult,
    BundleImportAttemptListOptions, BundleImportAttemptListResult, BundleImportAttemptOptions,
    BundleImportAttemptOutcomeSnapshot, BundleImportAttemptResult, BundleImportAttemptSnapshot,
    BundleImportPreflightOptions, BundleImportPreflightResult,
    BundleKnowledgeExposureLocalSourceRef, BundleKnowledgeExposureRef,
    BundleKnowledgeExposureSourceStatusRef, BundleKnowledgeExposureTransitionRef,
    BundleKnowledgeSpaceRef, BundleManifestValidationOptions, BundleManifestValidationResult,
    BundlePayloadExport, BundlePayloadExportOptions, BundlePayloadFile, BundlePayloadInput,
    BundlePayloadReference, BundlePayloadValidationOptions, BundlePayloadValidationResult,
    BundleRelationMembershipChangeRef, BundleRelationVersionRef,
    BundleVerificationRequirementIdentityRef, CheckpointCreateOptions, CheckpointCreateResult,
    CheckpointLatestOptions, CheckpointLatestResult, CheckpointListOptions, CheckpointListResult,
    CheckpointSnapshot, CheckpointValidationResult, CommitParentSnapshot, CommitSnapshot,
    DecisionRecordSupersedeCommit, DecisionRecordSupersedeOptions, EntityTransitionCommit,
    EntityTransitionOptions, EntityVersionDiff, EventListOptions, EventListResult, EventListTarget,
    EventSnapshot, EvidenceContentInput, EvidenceContentSnapshot, EvidenceCreateOptions,
    EvidenceCreateResult, EvidenceSnapshot, ExternalObjectRefListOptions,
    ExternalObjectRefListResult, ExternalObjectRefRecordOptions, ExternalObjectRefRecordResult,
    ExternalObjectRefSnapshot, ExternalObjectReferenceScope, GoalCreateCommit, GoalCreateOptions,
    GoalSnapshot, GoalState, GoalStatus, GoalTransitionCommit, GoalTransitionOptions, HistoryEntry,
    HistoryQueryOptions, HistoryQueryResult, HistoryStart, IntegrityReport, KnowledgeCreateCommit,
    KnowledgeCreateOptions, KnowledgeExposureAdoptOptions, KnowledgeExposureAdoptResult,
    KnowledgeExposureAdoptionCandidate, KnowledgeExposureAdoptionCandidateOptions,
    KnowledgeExposureAdoptionCandidateResult, KnowledgeExposureCreateLocalOptions,
    KnowledgeExposureCreateResult, KnowledgeExposureDerivedFromRelationCreateCommit,
    KnowledgeExposureDerivedFromRelationCreateOptions, KnowledgeExposureLifecycleStatus,
    KnowledgeExposureListOptions, KnowledgeExposureListResult,
    KnowledgeExposureLocalSourceSnapshot, KnowledgeExposureRefreshSourceStatusOptions,
    KnowledgeExposureRefreshSourceStatusResult, KnowledgeExposureSnapshot,
    KnowledgeExposureSourceStatus, KnowledgeExposureSourceStatusSnapshot,
    KnowledgeExposureWithdrawOptions, KnowledgeExposureWithdrawResult, KnowledgeListOptions,
    KnowledgeListResult, KnowledgeRelationCreateCommit, KnowledgeRelationCreateOptions,
    KnowledgeRelationListOptions, KnowledgeRelationListResult, KnowledgeRelationRemoveCommit,
    KnowledgeRelationRemoveOptions, KnowledgeRelationRestoreCommit,
    KnowledgeRelationRestoreOptions, KnowledgeRelationSnapshot, KnowledgeSnapshot,
    KnowledgeSpaceAvailableExposuresOptions, KnowledgeSpaceAvailableExposuresResult,
    KnowledgeSpaceCreateOptions, KnowledgeSpaceCreateResult,
    KnowledgeSpaceHistoricalExposuresOptions, KnowledgeSpaceHistoricalExposuresResult,
    KnowledgeSpaceListOptions, KnowledgeSpaceListResult,
    KnowledgeSpaceRefreshSourceStatusesOptions, KnowledgeSpaceRefreshSourceStatusesResult,
    KnowledgeSpaceSnapshot, KnowledgeSpaceSourceStaleExposuresOptions,
    KnowledgeSpaceSourceStaleExposuresResult, KnowledgeState, KnowledgeStatus,
    KnowledgeTransitionCommit, KnowledgeTransitionOptions, PlanCreateCommit, PlanCreateOptions,
    PlanSnapshot, PlanState, PlanStatus, PlanTransitionCommit, PlanTransitionOptions,
    PrimaryContainmentCreateCommit, PrimaryContainmentCreateOptions,
    PrimaryContainmentEndpointKind, PrimaryContainmentSnapshot, RecordCreateCommit,
    RecordCreateOptions, RecordKind, RecordKnowledgeRelationCreateCommit,
    RecordKnowledgeRelationCreateOptions, RecordKnowledgeRelationListOptions,
    RecordKnowledgeRelationListResult, RecordKnowledgeRelationRemoveCommit,
    RecordKnowledgeRelationRemoveOptions, RecordKnowledgeRelationRestoreCommit,
    RecordKnowledgeRelationRestoreOptions, RecordKnowledgeRelationSnapshot, RecordListOptions,
    RecordListResult, RecordRelationCreateCommit, RecordRelationCreateOptions,
    RecordRelationListOptions, RecordRelationListResult, RecordRelationRemoveCommit,
    RecordRelationRemoveOptions, RecordRelationRestoreCommit, RecordRelationRestoreOptions,
    RecordRelationSnapshot, RecordRelationType, RecordSnapshot, RecordState, RecordStatus,
    RecordTransitionCommit, RecordTransitionOptions, RelationVersionDiff, ReplayedState,
    ResolvedWhyQuerySubject, ResolvedWhyQueryTarget, ResolvedWorkStateDiffTarget,
    ResourceBindOptions, ResourceBindResult, ResourceBindingSnapshot, ResourceCreateOptions,
    ResourceCreateResult, ResourceObservationCreateOptions, ResourceObservationCreateResult,
    ResourceObservationDetailInput, ResourceObservationDetailSnapshot, ResourceObservationSnapshot,
    ResourceSnapshot, StoreLineageListOptions, StoreLineageListResult, StoreLineageRecordOptions,
    StoreLineageRecordResult, StoreLineageSnapshot, StoreMigrationAttemptSnapshot,
    StoreMigrationListOptions, StoreMigrationListResult, StoreMigrationOutcomeSnapshot,
    StoreMigrationRecordOptions, StoreMigrationRecordResult, StructuralReferenceCreateCommit,
    StructuralReferenceCreateOptions, StructuralReferenceEndpointKind, StructuralReferenceSnapshot,
    TaskAcceptanceCriterionRef, TaskCreateCommit, TaskCreateOptions,
    TaskSchedulingRelationCreateCommit, TaskSchedulingRelationCreateOptions,
    TaskSchedulingRelationSnapshot, TaskSchedulingRelationType, TaskSnapshot, TaskState,
    TaskStatus, TaskTransitionCommit, TaskTransitionOptions, VerificationApplicability,
    VerificationApplicabilityCacheSnapshot, VerificationApplicabilityRecordOptions,
    VerificationCreateCommit, VerificationCreateOptions, VerificationEvidenceRef,
    VerificationEvidenceRelationCreate, VerificationEvidenceRelationSnapshot,
    VerificationRequirementCreateCommit, VerificationRequirementCreateOptions,
    VerificationRequirementRevisionCommit, VerificationRequirementRevisionOptions,
    VerificationRequirementSnapshot, VerificationRequirementState, VerificationResourceBasis,
    VerificationResult, VerificationSemanticDependency, VerificationSnapshot, VerificationState,
    VerificationTarget, WhyDeferredRelationFamily, WhyEntityKind, WhyQueryOptions, WhyQueryResult,
    WhyQuerySubject, WhyQueryTarget, WhyRelationDirection, WhyRelationEdge, WhyRelationEndpoint,
    WhyRelationKind, WorkStateDiff, WorkStateDiffChangeKind, WorkStateDiffOptions,
    WorkStateDiffTarget, WorkStateRestoreCommit, WorkStateRestoreOptions, WorkspaceInfo,
    WorkspaceInitOptions, WorkspaceResourceAssociationOptions, WorkspaceResourceAssociationResult,
    WorkspaceResourceAssociationSnapshot,
};
pub use identity::{
    BranchId, ChangeSetId, CheckpointId, ClaimId, CommitId, Digest, EntityId, EntityVersionId,
    EventId, EvidenceId, ExposureId, ExposureTransitionId, ExternalObjectId, ExternalRefId,
    ExternalVersionId, ImportId, KnowledgeSpaceId, LineageId, MergeId, MergeItemId, MigrationId,
    OperationId, RelationId, RelationVersionId, ResourceId, ResourceObservationId, SessionDiffId,
    SessionId, StoreId, WorkspaceId,
};
pub use runtime::{
    ClaimLifecycleState, ClaimMode, ClaimNextOptions, ClaimNextResult, ClaimReleaseOptions,
    ClaimReleaseResult, ClaimSnapshot, ClaimTaskOptions, ClaimTaskResult,
};
pub use runtime::{ContextOverview, ContextOverviewOptions};
pub use runtime::{
    MergeAbortOptions, MergeAbortResult, MergeAttemptSnapshot, MergeContinueOptions,
    MergeContinueResult, MergeFreezeResolutionsOptions, MergeFreezeResolutionsResult,
    MergeItemClassification, MergeItemResolutionSnapshot, MergeItemSnapshot, MergeItemSubject,
    MergeListOptions, MergeListResult, MergeOutcome, MergeOutcomeSnapshot, MergeResolutionKind,
    MergeResolveOptions, MergeResolveResult, MergeRuntimeState, MergeStartOptions,
    MergeStartResult,
};
pub use runtime::{NextWorkOptions, NextWorkResult};
pub use runtime::{
    RunnableTaskBlockedReason, RunnableTaskCandidate, RunnableTaskClaimCoordination,
    RunnableTaskProjectionDimension, RunnableTasksOptions, RunnableTasksProjection,
};
pub use runtime::{
    SessionEndOptions, SessionEndResult, SessionFocus, SessionFocusOptions, SessionFocusPathEntry,
    SessionFocusUpdateResult, SessionLifecycleState, SessionSnapshot, SessionStartOptions,
    SessionStartResult, SessionSwitchOptions, SessionSwitchResult,
};
pub use store::{StoreInfo, StoreInitOptions, StoreManifest};
